sudo: required

services:
  - docker 

language: node_js

node_js:
  - "stable"
  
cache:
  directories:
  - node_modules
  
before_install:
  - docker build -t shashi/react-rickandmontry -f ./client/Dockerfile ./client 

script:

  - docker run -e CI=true shashi/react-rickandmontry npm run test 