language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t shashi2030/rickandmontry -f Dockerfile.dev .

script:
  - docker run -e CI=true shashi2030/rickandmontry

deploy:
  provider: heroku
  api_key:
    secure: $heroku_token
  skip_cleanup: true
  app: rick-client
  on: 
    branch: master