language: generic
sudo: required
services:
- docker
before_install:
- docker build -t shashi2030/rick-client -f Dockerfile.dev .
script:
- docker run -e CI=true shashi2030/rick-client
deploy:
  provider: heroku
  api_key:
    secure: Jd57GKikKLKTJsCDEtpWbsS+RzT0gcYHFDN6RW0c0i5xL8tqgFC07gqnLHZDRNgDNp/sFc4d8iAgGyTyqBXCKjPGXSfKGCDj94bAUzNzQq1WeEiHB7C70h/IXv0/oCXxZx9wk2WLtBDSGHDCjqAfR183Vq9pZwIXFcCkT4ZHw19nWo+NLuLwHc2y3feQj+++mpE301vP++rlAYlinfr1RNpwGz5ZClu5jN61aG3py0t2xp/l8vpo6ktsQaRagsS/zPbPil5cyCe5sWx/JW6vLTNMvKrZdiX0G5+P+sRjcMS5vKu4sNFxmk2Fjqq7j8nbkRLc8eOEss3NUimGS9yzQ3QNoRqhwFoCAe4mltcth6wU+5x6kMuMpehKDofso1nZrCB1ZWvcdoiuvM5bRqFdyIRtMkyxxFrB5sV6irz8ezSBxwZp06aaTHvjN92Hmdtlo3ugJyJ0CtVU4Qzz0h84saMGWUL3lY+4CNNIIeOUWum6V/wkg22FrK2W7lOFjs8Q8e/z+P5fdQibDi/z4CBTZ+rERMDhfs8Z0BjpcZSHiurxr6AMQqV+QU5nHvT7p+zHdToLjbP9Ha1el72S16CS2X3fJWAumiszBeLSl1LMFrISbjISbONZ8mziQBxpkzsVrhm5SBEDOL8F1s52iipFDhuR0ZyEVENQ2GCuj6etErc=
  skip_cleanup: true
  app: rick-client
  on:
    repo: shashi2030/rick-client
