language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t shashi2030/rickandmontry -f Dockerfile.dev .

script:
  - docker run -e CI=true shashi2030/rickandmontry

deploy:
  provider: heroku
  api_key:
    secure: "IHR4R6oG9A8s0EMs3XMyxndw4L5LB3r0RC9rIaKf4wEFro4P2Vu4aB/SYDeTO1jtG2NCL94H64qswF3zM9eL17rjcV8YbeYvANLL5XtUVj9d0mcOCqIQ29fRnDDOTMDCO4M43t6UjEqP2Y3HyFTrKrDOy2R7+DKI0AfvCf2VlD77JHGzn0SYjrAVBD3fmBMKItPvIxCcnRyFg65uUC+HFFHlOWy6ziiPSl9Bvt4oWyEjf01GHBiixayoqro3Owm8piGdg4jBUvS0Tj52cO3GEiqhs7FyQHco+ZzSsfYCKNqiZ2LBUArrHcXV90ongEQ8n1RXpAxPAxqXcPet8JsUn57lYBZozdnF9LX5nfKuKXpFgD/s3IgWy2FkvobggQ3/NnTK+I06fxPpqQ5eP16LMEfxDUIk75AgJKqQEf4HnMjQn+RAytQ8QetQ4qRrqcsZ7/i/XEuJVaPiGt2L9thMltKuQep4XPi4+Da1DnQDflwNUkVgxTLm3ESC8QD9EN1Jz3ifi2tKQKnN6YWQMLLGvMZ+pptQGjOjkzGxRc3w1+2mOEUWmoenGPasv1hSGBoCXTVMx/FZZPGCZPky6UiHsHXVhcBxy4Lgv4g0kTQd6VqBs7M2F1vBOY0VWLnBtVn5xGnFg188GFn8XaCHimO4ymEXlcGFZy4OMyY7rMGK/Ac="
  skip_cleanup: true
  app: rick-client
  on: 
    branch: master