language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t shashi2030/rickandmontry -f Dockerfile.dev .

script:
  - docker run -e CI=true shashi2030/rickandmontry

deploy:
  provider: heroku
  api_key:
    secure: "e3622139-8936-4203-9b4a-97fe5b4ffe4a"
  skip_cleanup: true
  app: rick-client
  on: 
    branch: master