language: generic
sudo: required
services:
- docker
before_install:
- docker build -t shashi2030/rick-client -f Dockerfile.prod .
script:
- docker run -e CI=true shashi2030/rick-client
deploy:
  provider: heroku
  api_key:
    secure: $APP_TOKEN
  skip_cleanup: true
  app: rick-client
  on:
    all_branches: true
