language: generic
sudo: required
services:
- docker
before_install:
- docker build -t shashi2030/rick-client -f Dockerfile.dev .
script:
- docker run -e CI=true shashi2030/rick-client
deploy:
  provider: heroku
  api_key:
    secure: "mX12FuEQlMZoZDpCi37ny9aVdVdq+LKjR8WIZXQOOd+KB0zkKNKVdsK0vxySoZ9Zk55QYUUPFcpE/NEXG9aGh9eBFLDothwh46We33Xo5yPMcblwlDj/fzsC0R5eE0pPaCXPZN5gZ2WSM6dsXCm+cW01KfuSG1pRSWREJx3NIzwJQ2qEtngq5gB8ZYpJ1u7R33kcNkTZN0Z+m44byRP1OekFbkkUAgEUu1k/gwruEHS8boTzP43q4enlM90iw5jBcTvuBhZa8unYHZoYR6pJuqINOddThkq2b8rYaAZRgLueYqqD0aMQyZ33t7HHEiyCNNJOxCO+5gB/2bdabbDa++MWKrnzVZVeWHwd9vgpiGyNy7wo0eNjV97OajX5qPp/xuT0l77WfFG0zEVXJggUqd2WADxi0ttgeohHt10hguVNGt0wtaLwf7Ul4rWD0NzI+yIuM06jZOoGXyRGRz6BEBqwkjHu0X7aKIYx5b/W8iyUyy23MkpaF8Nzsu3sTYA331sgol4vSZo3HwLPefpgTZo6fcIJAjpYSjqCE7/2hGFBi0ffRCrMvgp0gTMwBoby3xBm3iCaI4isxuruq73Tl/9XsuXEDawUXnHeNFjVdKNDX0QjA9s7ujQyf1r4nUVuzJ4Is0YE7HeaycYU7ys82NrXsX4Dq7931aoBZUyg4ME="
  skip_cleanup: true
  app: rick-client
  on:
    repo: shashi2030/rick-client
